version: "3.7"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - ${DATA_FOLDER}/caddy_config:/config
      - ${DATA_FOLDER}/caddy_config/Caddyfile:/etc/caddy/Caddyfile

  n8n:
    image: docker.n8n.io/n8nio/n8n:next
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env        # your existing env file
      - .env-n8n-ai # new secrets file
    environment:
      - N8N_HOST=${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=3
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - N8N_REDIS_PASSWORD=dummy_password
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
    volumes:
      - /mnt/volume_fra1_01/n8n_data:/home/node/.n8n
      - ${DATA_FOLDER}/local_files:/files

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    command: ["redis-server", "--requirepass", "dummy_password"]
    volumes:
      - /mnt/volume_fra1_01/redis_data:/data

  nocodb:
    image: nocodb/nocodb:latest
    restart: always
    expose:
      - "8080"
    volumes:
      - /mnt/volume_fra1_01/nocodb_data:/usr/app/data
    environment:
      - NC_AUTH_BASIC_USER=admin
      - NC_AUTH_BASIC_PASS=${NOCO_PASSWORD}  # set this variable in your .env file

  qdrant:
    image: qdrant/qdrant
    restart: always
    expose:
      - "6333"
    volumes:
      - /mnt/volume_fra1_01/qdrant_storage:/qdrant/storage

  siyuan:
    image: b3log/siyuan
    restart: unless-stopped
    expose:
      - "6806"
    command: 
      - "--workspace=/siyuan/workspace/"
      - "--accessAuthCode=${SIYUAN_AUTH_CODE}"
    volumes:
      - /mnt/volume_fra1_01/siyuan_data:/siyuan/workspace
    environment:
      - TZ=${GENERIC_TIMEZONE}
      - PUID=1000
      - PGID=1000

volumes:
  caddy_data:
    external: true
